# Generated by Django 3.2.9 on 2021-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(max_length=100, verbose_name='short description'),
        ),
    ]
